"use client";
import Link from "next/link";
import {useCallback,useEffect,useRef,useState} from "react";
import {subjects} from "@/lib/data";
import {displayDate,filterCalendar,madridDate,madridInput,monthCells,occursOn,relativeDay,shiftDate,sourceLabels,upcomingCalendar,type CalendarData,type CalendarEvent} from "@/lib/calendar";
import {dashboardFetch,academicUpdated} from "@/lib/dashboard-client";

const typeLabels:Record<string,string>={activity:"Actividad",exam:"Examen / cuestionario",deadline:"Entrega",holiday:"Festivo",other:"Otro",assignment:"Tarea",resource:"Recurso",forum:"Foro",announcement:"Avisos",content:"Contenido"};
function eventHref(e:CalendarEvent){return `/dashboard/calendario?source=${e.source}&event=${e.id}`;}
export function UpcomingEvents(){
 const [data,setData]=useState<CalendarData|null>(null);const [error,setError]=useState("");const generation=useRef(0);
 const load=useCallback(()=>{const sequence=++generation.current;const today=madridDate();dashboardFetch<CalendarData>(`/api/calendar?from=${today}&to=${shiftDate(today,180)}`).then(value=>{if(sequence===generation.current){setData(value);setError("");}}).catch(e=>{if(sequence===generation.current)setError(e.message);});},[]);
 useEffect(()=>{load();window.addEventListener("smr:academic-updated",load);return()=>{generation.current++;window.removeEventListener("smr:academic-updated",load);};},[load]);
 const events=upcomingCalendar(data?.events||[]).slice(0,5);
 return <section className="panel mb-6"><div className="flex flex-wrap justify-between gap-3"><h2 className="font-semibold text-lg">Próximos eventos</h2><Link className="text-brand text-sm" href="/dashboard/calendario">Ver calendario →</Link></div>{error&&<p className="message error mt-3" role="alert">{error}</p>}<div className="divide-y divide-[#223047]">{events.map(e=><Link className="flex items-start gap-4 py-4" key={`${e.source}:${e.id}`} href={eventHref(e)}><span className="muted text-sm shrink-0 w-20">{relativeDay(e.start_date||madridDate(e.start_at))}</span><div className="min-w-0"><p className="font-medium break-words">{e.title}</p><p className="muted mt-1 text-xs">{e.subject?`${e.subject} · `:""}{sourceLabels[e.source]} · {displayDate(e)}</p>{e.completed&&<span className="text-xs text-green-300">Completado</span>}</div></Link>)}</div>{data&&!events.length&&<p className="muted text-sm mt-4">No hay eventos próximos en los siguientes seis meses.</p>}{!data&&!error&&<p className="muted text-sm mt-4">Cargando fechas…</p>}{data?.truncated&&<p className="muted text-xs">Hay más eventos; consulta un intervalo más pequeño en el calendario.</p>}</section>;
}

export function CalendarPanel({deepLink}:{deepLink?:{source:string;id:string}}){
 const [month,setMonth]=useState(()=>madridDate().slice(0,7));const [data,setData]=useState<CalendarData|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);
 const [source,setSource]=useState("all");const [subject,setSubject]=useState("");const [agenda,setAgenda]=useState(false);const [selected,setSelected]=useState<CalendarEvent|null>(null);const [form,setForm]=useState(false);const [editing,setEditing]=useState<CalendarEvent|null>(null);const [allDay,setAllDay]=useState(false);const [notice,setNotice]=useState("");
 const [formSource,setFormSource]=useState("personal");const requestId=useRef(0);const detail=useRef<HTMLDivElement>(null);
 const cells=monthCells(month);const from=cells[0];const to=shiftDate(cells[41],1);
 const load=useCallback(()=>{const id=++requestId.current;setLoading(true);dashboardFetch<CalendarData>(`/api/calendar?from=${from}&to=${to}`).then(value=>{if(id===requestId.current){setData(value);setError("");setSelected(previous=>previous?value.events.find(e=>e.source===previous.source&&e.id===previous.id)||previous:null);}}).catch(e=>{if(id===requestId.current)setError(e.message);}).finally(()=>{if(id===requestId.current)setLoading(false);});},[from,to]);
 useEffect(()=>{load();window.addEventListener("smr:academic-updated",load);return()=>{requestId.current++;window.removeEventListener("smr:academic-updated",load);};},[load]);
 useEffect(()=>{if(!deepLink)return;const abort=new AbortController();dashboardFetch<CalendarData>(`/api/calendar?source=${encodeURIComponent(deepLink.source)}&event=${encodeURIComponent(deepLink.id)}`,"GET",undefined,abort.signal).then(value=>{if(!abort.signal.aborted){const event=value.events[0];setSelected(event);if(event.has_date!==false)setMonth(madridDate(event.start_at).slice(0,7));}}).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[deepLink?.id,deepLink?.source]);
 useEffect(()=>{if(selected)detail.current?.scrollIntoView({behavior:"smooth",block:"nearest"});},[selected?.id]);
 const filtered=filterCalendar(data?.events||[],source,subject);const monthEvents=filtered.filter(e=>cells.some(day=>day.slice(0,7)===month&&occursOn(e,day)));
 const canEdit=selected&&selected.source!=="moodle"&&(selected.source==="personal"||data?.is_admin);
 async function mutate(method:string,body:Record<string,unknown>){setBusy(true);setError("");setNotice("");try{await dashboardFetch("/api/calendar",method,body);setNotice(method==="DELETE"?"Evento eliminado.":"Evento guardado.");setForm(false);if(method==="DELETE")setSelected(null);academicUpdated();return true;}catch(e){setError(e instanceof Error?e.message:"No se ha podido guardar el evento.");return false;}finally{setBusy(false);}}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fields=new FormData(e.currentTarget);const get=(key:string)=>String(fields.get(key)||"");const success=await mutate(editing?"PATCH":"POST",{source:get("source"),...(editing?{id:editing.id}:{}),title:get("title"),description:get("description"),subject:get("subject")||null,start:get("start"),end:get("end"),all_day:allDay,event_type:get("event_type"),...(get("source")==="personal"?{reminder_enabled:fields.get("reminder_enabled")==="on"}:{})});if(success){setMonth(get("start").slice(0,7));setSelected(null);}}
 async function toggleMoodle(field:"read"|"completed"|"favourite"|"hidden"){if(!selected)return;setBusy(true);setError("");try{await dashboardFetch("/api/moodle/sync","PATCH",{kind:"event",id:selected.id,[field]:!selected[field]});setSelected({...selected,[field]:!selected[field]});academicUpdated();}catch(e){setError(e instanceof Error?e.message:"No se pudo actualizar el estado.");}finally{setBusy(false);}}
 function move(delta:number){const date=new Date(`${month}-01T12:00:00Z`);date.setUTCMonth(date.getUTCMonth()+delta);setMonth(date.toISOString().slice(0,7));}
 return <><header className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">1ºD SMR</p><h1 className="text-3xl font-semibold mt-3">Calendario</h1><p className="muted text-sm mt-3">Fechas de clase y tu agenda personal · Europe/Madrid</p></div><button className="primary" disabled={busy||!data} onClick={()=>{setEditing(null);setFormSource("personal");setAllDay(false);setForm(true);setSelected(null);}}>+ Nuevo evento</button></header>
 {error&&<p className="message error mb-4" role="alert">{error}</p>}{notice&&<p className="message mb-4" role="status">{notice}</p>}
 {form&&<section className="panel mb-6"><h2 className="text-lg font-semibold mb-4">{editing?"Editar evento":"Nuevo evento"}</h2><form key={editing?.id||"new"} onSubmit={save} className="field-grid sm:grid-cols-2"><label>Tipo de agenda<select name="source" value={formSource} onChange={e=>setFormSource(e.target.value)} disabled={Boolean(editing)}>{(!editing||editing.source==="personal")&&<option value="personal">👤 Personal</option>}{data?.is_admin&&(!editing||editing.source==="general")&&<option value="general">👥 General de clase</option>}</select>{editing&&<input type="hidden" name="source" value={editing.source}/>}</label><label>Tipo de evento<select name="event_type" defaultValue={editing?.event_type||"activity"}>{["activity","exam","deadline","holiday","other"].map(type=><option key={type} value={type}>{typeLabels[type]}</option>)}</select></label><label>Título<input name="title" required maxLength={160} defaultValue={editing?.title}/></label><label>Asignatura opcional<select name="subject" defaultValue={editing?.subject||""}><option value="">Sin asignatura</option>{subjects.map(s=><option key={s}>{s}</option>)}</select></label><label className="flex items-center gap-2 sm:col-span-2"><input type="checkbox" checked={allDay} onChange={e=>setAllDay(e.target.checked)}/>Todo el día</label><label>Inicio<input key={`start-${allDay}`} name="start" type={allDay?"date":"datetime-local"} required min={allDay?"1900-01-01":"1900-01-01T00:00"} max={allDay?"9998-12-31":"9998-12-31T23:59"} defaultValue={editing?allDay?editing.start_date||madridDate(editing.start_at):madridInput(editing.start_at):allDay?`${month}-01`:`${month}-01T09:00`}/></label><label>{allDay?"Último día (opcional)":"Fin (opcional)"}<input key={`end-${allDay}`} name="end" type={allDay?"date":"datetime-local"} defaultValue={editing?allDay?editing.end_date||"":editing.end_at?madridInput(editing.end_at):"":""}/></label><label className="sm:col-span-2">Descripción<textarea name="description" maxLength={4000} defaultValue={editing?.description}/></label>{formSource==="personal"&&<label className="flex items-center gap-2 sm:col-span-2"><input name="reminder_enabled" type="checkbox" defaultChecked={editing?.reminder_enabled??true}/>Recordatorios para este evento</label>}<p className="muted text-xs sm:col-span-2">Las horas se interpretan en Madrid. En la hora repetida de otoño se utiliza la primera aparición.</p><div className="flex gap-3 sm:col-span-2"><button disabled={busy} className="primary">{busy?"Guardando…":"Guardar"}</button><button className="secondary" type="button" disabled={busy} onClick={()=>setForm(false)}>Cancelar</button></div></form></section>}
 {selected&&<section ref={detail} className="panel mb-6" aria-label="Detalle del evento"><div className="flex justify-between gap-3"><div className="min-w-0"><p className="eyebrow">{sourceLabels[selected.source]} · {typeLabels[selected.event_type]||"Actividad"}</p><h2 className="text-xl font-semibold mt-3 break-words">{selected.title}</h2></div><button className="small-button h-fit" onClick={()=>setSelected(null)}>Cerrar</button></div><p className="muted mt-2 text-sm">{selected.subject}</p><p className="mt-3">{selected.has_date===false?"Sin fecha":displayDate(selected)}{selected.end_at&&!selected.all_day?` — ${displayDate({...selected,start_at:selected.end_at})}`:selected.all_day&&selected.end_date!==selected.start_date?` · Hasta ${selected.end_date}`:""}</p>{selected.description&&<p className="muted text-sm mt-3 whitespace-pre-wrap break-words">{selected.description}</p>}{selected.source!=="general"&&<p className="text-sm mt-3">{selected.completed?"✓ Completado":"No completado"}{selected.read?" · Leído":""}{selected.hidden?" · Oculto":""}{selected.favourite?" · Favorito":""}</p>}
 <div className="flex flex-wrap gap-2 mt-4">{selected.source==="moodle"&&<>{selected.external_url&&<a className="primary" href={selected.external_url} target="_blank" rel="noopener noreferrer">Abrir en Aula Virtual ↗</a>}{(["read","completed","favourite","hidden"] as const).map(field=><button className="secondary" disabled={busy} key={field} onClick={()=>toggleMoodle(field)}>{field==="read"?selected.read?"Marcar pendiente":"Marcar leído":field==="completed"?selected.completed?"Desmarcar completado":"Completar":field==="favourite"?selected.favourite?"Quitar favorito":"Favorito":selected.hidden?"Mostrar":"Ocultar"}</button>)}</>}{canEdit&&<><button className="secondary" disabled={busy} onClick={()=>{setEditing(selected);setFormSource(selected.source);setAllDay(selected.all_day);setForm(true);}}>Editar</button><button className="secondary text-red-300" disabled={busy} onClick={()=>{if(window.confirm(`¿Eliminar «${selected.title}»?`))void mutate("DELETE",{source:selected.source,id:selected.id});}}>Eliminar</button></>}{selected.source==="personal"&&<button disabled={busy} className="secondary" onClick={async()=>{if(await mutate("PATCH",{source:"personal",id:selected.id,completed:!selected.completed}))setSelected({...selected,completed:!selected.completed});}}>{selected.completed?"Desmarcar completado":"Completar"}</button>}</div></section>}
 <section className="panel"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2 items-center"><button className="small-button" aria-label="Mes anterior" onClick={()=>move(-1)}>←</button><h2 className="font-semibold capitalize">{new Intl.DateTimeFormat("es-ES",{month:"long",year:"numeric",timeZone:"Europe/Madrid"}).format(new Date(`${month}-15T12:00:00Z`))}</h2><button className="small-button" aria-label="Mes siguiente" onClick={()=>move(1)}>→</button></div><div className="flex gap-2"><button className="small-button" onClick={()=>setMonth(madridDate().slice(0,7))}>Hoy</button><button className="small-button hidden md:block" aria-pressed={agenda} onClick={()=>setAgenda(!agenda)}>{agenda?"Vista mensual":"Vista agenda"}</button><button className="small-button" onClick={load}>Actualizar</button></div></div>
 <div className="flex flex-wrap gap-2 mt-5" aria-label="Filtrar calendario">{[["all","Todos"],["moodle","🏫 Aula Virtual"],["general","👥 Generales"],["personal","👤 Personales"]].map(([value,label])=><button aria-pressed={source===value} className={`small-button ${source===value?"bg-blue-400/20 text-blue-200":"muted"}`} key={value} onClick={()=>setSource(value)}>{label}</button>)}</div><label className="mt-3 max-w-md">Asignatura<select value={subject} onChange={e=>setSubject(e.target.value)}><option value="">Todas las asignaturas</option>{subjects.map(s=><option key={s}>{s}</option>)}</select></label>{loading&&<p className="muted text-xs mt-3" role="status">Cargando calendario…</p>}
 {!agenda&&<div className="calendar-month mt-5"><div className="grid grid-cols-7 gap-px text-center muted text-xs mb-2">{["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"].map(day=><span key={day}>{day}</span>)}</div><div className="grid grid-cols-7 gap-px bg-[#223047] rounded-xl overflow-hidden">{cells.map(day=>{const events=filtered.filter(e=>occursOn(e,day));return <div key={day} className={`calendar-day min-w-0 p-2 bg-[#0e1726] ${day.slice(0,7)!==month?"opacity-60":""}`}><p className={`text-xs mb-2 ${day===madridDate()?"text-blue-300 font-bold":"muted"}`}>{Number(day.slice(-2))}</p>{events.slice(0,3).map(e=><button key={`${e.source}:${e.id}`} className={`calendar-entry calendar-${e.source}`} onClick={()=>{setSelected(e);setForm(false);}} title={e.title}><span>{e.source==="moodle"?"🏫":e.source==="general"?"👥":"👤"}</span><span className="truncate">{e.title}</span></button>)}{events.length>3&&<button className="text-xs text-brand" onClick={()=>setAgenda(true)}>+{events.length-3} más</button>}</div>;})}</div></div>}
 <div className={agenda?"mt-5":"calendar-agenda mt-5"}><p className="muted text-xs mb-3">Agenda del mes · Las actividades ocultas no aparecen.</p><div className="divide-y divide-[#26364e]">{monthEvents.map(e=><button key={`${e.source}:${e.id}`} onClick={()=>{setSelected(e);setForm(false);}} className="text-left w-full py-4 flex gap-4"><span className="muted text-sm w-20 shrink-0">{relativeDay(e.start_date||madridDate(e.start_at))}</span><span className="min-w-0"><span className="block font-medium break-words">{e.title}</span><span className="block muted text-xs mt-1">{sourceLabels[e.source]} · {e.subject?`${e.subject} · `:""}{displayDate(e)}{e.completed?" · Completado":""}</span></span></button>)}</div>{!monthEvents.length&&!loading&&<p className="muted py-5 text-sm">No hay eventos con estos filtros.</p>}</div>{data?.truncated&&<p className="message mt-3 text-sm">Hay más de 500 eventos en alguna fuente. Reduce el intervalo para ver más detalles.</p>}
 </section></>;
}
