"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {defaultPreferences,type NotificationPreferences} from "@/lib/reminders";
import {dashboardFetch} from "@/lib/dashboard-client";
type Settings={preferences:NotificationPreferences;last_sync:{started_at:string;finished_at:string|null;result:string;mode:string}|null};
export function NotificationPreferencesPanel(){
 const [settings,setSettings]=useState<Settings|null>(null);const [prefs,setPrefs]=useState(defaultPreferences);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 useEffect(()=>{const abort=new AbortController();dashboardFetch<Settings>("/api/preferences","GET",undefined,abort.signal).then(data=>{setSettings(data);setPrefs(data.preferences);}).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{setSettings(await dashboardFetch<Settings>("/api/preferences","PATCH",prefs));setMessage("Preferencias guardadas.");}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar.");}finally{setBusy(false);}}
 return <section className="panel max-w-xl mb-6"><h2 className="text-lg font-semibold">Preferencias de avisos</h2><p className="muted text-sm mt-2">Los avisos se comprueban automáticamente sin dejar el navegador abierto, cuando el servicio esté activado.</p>{error&&<p role="alert" className="message error mt-3">{error}</p>}{message&&<p role="status" className="message mt-3">{message}</p>}<form onSubmit={save} className="field-grid mt-5"><fieldset><legend className="font-medium text-sm mb-3">Avísame</legend><div className="space-y-3">{[7,3,1,0].map(day=><label className="flex items-center gap-3" key={day}><input type="checkbox" checked={prefs.days.includes(day)} disabled={busy||!settings} onChange={e=>setPrefs({...prefs,days:e.target.checked?[...prefs.days,day]:prefs.days.filter(d=>d!==day)})}/>{day===0?"El mismo día":`${day} ${day===1?"día":"días"} antes`}</label>)}</div></fieldset><fieldset><legend className="font-medium text-sm mb-3">Canales</legend><label className="flex items-center gap-3 mb-3"><input type="checkbox" checked={prefs.internal_enabled} disabled={busy||!settings} onChange={e=>setPrefs({...prefs,internal_enabled:e.target.checked})}/>Notificación SMR HUB</label><label className="flex items-center gap-3"><input type="checkbox" checked={prefs.email_enabled} disabled={busy||!settings} onChange={e=>setPrefs({...prefs,email_enabled:e.target.checked})}/>Email de recordatorios</label></fieldset><p className="muted text-xs">Los avisos se programan a las 09:00 de Madrid. Para una entrega del mismo día anterior a esa hora, se revisan desde medianoche. No se avisa de eventos completados, ocultos o vencidos. El email requiere que el servicio esté configurado.</p><button className="primary w-fit" disabled={busy||!settings}>{busy?"Guardando…":"Guardar"}</button></form><p className="muted text-xs mt-5">Última sincronización: {settings?.last_sync?`${new Date(settings.last_sync.finished_at||settings.last_sync.started_at).toLocaleString("es-ES",{timeZone:"Europe/Madrid"})} · ${settings.last_sync.result==="success"?"Completada":settings.last_sync.result==="running"?"En curso":"No completada"}`:"Pendiente"}</p><Link className="text-brand text-sm mt-3 inline-block" href="/dashboard/aula-virtual">Sincronizar manualmente →</Link></section>;
}
